# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15sUdzI94oTUY7nukqlnskMxGU0gANDvd
"""

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

# 1. Page Configuration (Wide layout, dark theme feel)
st.set_page_config(
    page_title="Retail Demand Planning",
    page_layout="wide",
    initial_sidebar_state="expanded",
)

# 2. Inject Custom CSS to Match the Editorial Mockup Design
st.markdown(
    """

""",
    unsafe_allow_html=True,
)

# 3. Header Section (Matching Editorial Style)
st.markdown(
    '